# Generated by Django 4.0.7 on 2024-08-06 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='baseuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', related_query_name='board_obj', to=settings.AUTH_USER_MODEL),
        ),
    ]
