# Generated by Django 4.0.7 on 2024-08-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_board_baseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='user_that_should_done',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='members',
        ),
        migrations.DeleteModel(
            name='MemberJoined',
        ),
    ]
